### ISSUE TITLE
Mac的直接打包后，选择一篇文章，点击下载，就挂了

### ISSUE THREAD

**Issue by LaughSun0513** [xiaoguyu/wechatDownload#1]
Uncaught Exception:
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('AxiosError: read ECONNRESET\n' +
'    at AxiosError.from (/wechatDownload/dist/mac/wechatDownload.app/Contents/Resources/app.asar/node_modules/axios/dist/node/axios.cjs:789:14)\n' +
'    at RedirectableRequest.handleRequestError (/wechatDownload/dist/mac/wechatDownload.app/Contents/Resources/app.asar/node_modules/axios/dist/node/axios.cjs:2744:25)\n' +
'    at RedirectableRequest.emit (node:events:527:28)\n' +
'    at eventHandlers.<computed> (/wechatDownload/dist/mac/wechatDownload.app/Contents/Resources/app.asar/node_modules/follow-redirects/index.js:14:24)\n' +
'    at ClientRequest.emit (node:events:527:28)\n' +
'    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n' +
'    at TLSSocket.emit (node:events:527:28)\n' +
'    at emitErrorNT (node:internal/streams/destroy:157:8)\n' +
'    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n' +
'    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {\n' +
"  syscall: 'read',\n" +
"  code: 'ECONNRESET',\n" +
'  errno: -54,\n' +
'  config: {\n' +
'    transitional: {\n' +
'      silentJSONParsing: true,\n' +
'      forcedJSONParsing: true,\n' +
'      clarifyTimeoutError: false\n' +
'    },\n' +
"    adapter: [ 'xhr', 'http' ],\n" +
'    transformRequest: [ [Function: transformRequest] ],\n' +
'    transformResponse: [ [Function: transformResponse] ],\n' +
'    timeout: 0,\n' +
"    xsrfCookieName: 'XSRF-TOKEN',\n" +
"    xsrfHeaderName: 'X-XSRF-TOKEN',\n" +
'    maxContentLength: -1,\n' +
'    maxBodyLength: -1,\n' +
'    env: { FormData: [Function], Blob: null },\n' +
'    validateStatus: [Function: validateStatus],\n' +
'    headers: AxiosHeaders {\n' +
"      Accept: 'application/json, text/plain, */*',\n" +
"      'User-Agent': 'axios/1.2.2',\n" +
"      'Accept-Encoding': 'gzip, compress, deflate, br'\n" +
'    },\n' +
"    method: 'get',\n" +
"    url: 'https://mp.weixin.qq.com/s/4NLAPpg17z96SXiI1XYEWg',\n" +
'    data: undefined\n' +
'  },\n' +
'  request: <ref *1> Writable {\n' +
'    _writableState: WritableState {\n' +
'      objectMode: false,\n' +
'      highWaterMark: 16384,\n' +
'      finalCalled: false,\n' +
'      needDrain: false,\n' +
'      ending: false,\n' +
'      ended: false,\n' +
'      finished: false,\n' +
'      destroyed: false,\n' +
'      decodeStrings: true,\n' +
"      defaultEncoding: 'utf8',\n" +
'      length: 0,\n' +
'      writing: false,\n' +
'      corked: 0,\n' +
'      sync: true,\n' +
'      bufferProcessing: false,\n' +
'      onwrite: [Function: bound onwrite],\n' +
'      writecb: null,\n' +
'      writelen: 0,\n' +
'      afterWriteTickInfo: null,\n' +
'      buffered: [],\n' +
'      bufferedIndex: 0,\n' +
'      allBuffers: true,\n' +
'      allNoop: true,\n' +
'      pendingcb: 0,\n' +
'      constructed: true,\n' +
'      prefinished: false,\n' +
'      errorEmitted: false,\n' +
'      emitClose: true,\n' +
'      autoDestroy: true,\n' +
'      errored: null,\n' +
'      closed: false,\n' +
'      closeEmitted: false,\n' +
'      [Symbol(kOnFinished)]: []\n' +
'    },\n' +
'    _events: [Object: null prototype] {\n' +
'      response: [Function: handleResponse],\n' +
'      error: [Function: handleRequestError],\n' +
'      socket: [Function: handleRequestSocket]\n' +
'    },\n' +
'    _eventsCount: 3,\n' +
'    _maxListeners: undefined,\n' +
'    _options: {\n' +
'      maxRedirects: 21,\n' +
'      maxBodyLength: Infinity,\n' +
"      protocol: 'https:',\n" +
"      path: '/s/4NLAPpg17z96SXiI1XYEWg',\n" +
"      method: 'GET',\n" +
'      headers: [Object: null prototype],\n' +
'      agents: [Object],\n' +
'      auth: undefined,\n' +
'      beforeRedirect: [Function: dispatchBeforeRedirect],\n' +
'      beforeRedirects: [Object],\n' +
"      hostname: 'mp.weixin.qq.com',\n" +
"      port: '',\n" +
'      agent: undefined,\n' +
'      nativeProtocols: [Object],\n' +
"      pathname: '/s/4NLAPpg17z96SXiI1XYEWg'\n" +
'    },\n' +
'    _ended: true,\n' +
'    _ending: true,\n' +
'    _redirectCount: 0,\n' +
'    _redirects: [],\n' +
'    _requestBodyLength: 0,\n' +
'    _requestBodyBuffers: [],\n' +
'    _onNativeResponse: [Function (anonymous)],\n' +
'    _currentRequest: ClientRequest {\n' +
'      _events: [Object: null prototype],\n' +
'      _eventsCount: 7,\n' +
'      _maxListeners: undefined,\n' +
'      outputData: [],\n' +
'      outputSize: 0,\n' +
'      writable: true,\n' +
'      destroyed: false,\n' +
'      _last: true,\n' +
'      chunkedEncoding: false,\n' +
'      shouldKeepAlive: false,\n' +
'      maxRequestsOnConnectionReached: false,\n' +
'      _defaultKeepAlive: true,\n' +
'      useChunkedEncodingByDefault: false,\n' +
'      sendDate: false,\n' +
'      _removedConnection: false,\n' +
'      _removedContLen: false,\n' +
'      _removedTE: false,\n' +
'      _contentLength: 0,\n' +
'      _hasBody: true,\n' +
"      _trailer: '',\n" +
'      finished: true,\n' +
'      _headerSent: true,\n' +
'      _closed: false,\n' +
'      socket: [TLSSocket],\n' +
"      _header: 'GET /s/4NLAPpg17z96SXiI1XYEWg HTTP/1.1\\r\\n' +\n" +
"        'Accept: application/json, text/plain, */*\\r\\n' +\n" +
"        'User-Agent: axios/1.2.2\\r\\n' +\n" +
"        'Accept-Encoding: gzip, compress, deflate, br\\r\\n' +\n" +
"        'Host: mp.weixin.qq.com\\r\\n' +\n" +
"        'Connection: close\\r\\n' +\n" +
"        '\\r\\n',\n" +
'      _keepAliveTimeout: 0,\n' +
'      _onPendingData: [Function: nop],\n' +
'      agent: [Agent],\n' +
'      socketPath: undefined,\n' +
"      method: 'GET',\n" +
'      maxHeaderSize: undefined,\n' +
'      insecureHTTPParser: undefined,\n' +
"      path: '/s/4NLAPpg17z96SXiI1XYEWg',\n" +
'      _ended: false,\n' +
'      res: [IncomingMessage],\n' +
'      aborted: false,\n' +
'      timeoutCb: null,\n' +
'      upgradeOrConnect: false,\n' +
'      parser: null,\n' +
'      maxHeadersCount: null,\n' +
'      reusedSocket: false,\n' +
"      host: 'mp.weixin.qq.com',\n" +
"      protocol: 'https:',\n" +
'      _redirectable: [Circular *1],\n' +
'      [Symbol(kCapture)]: false,\n' +
'      [Symbol(kNeedDrain)]: false,\n' +
'      [Symbol(corked)]: 0,\n' +
'      [Symbol(kOutHeaders)]: [Object: null prototype]\n' +
'    },\n' +
"    _currentUrl: 'https://mp.weixin.qq.com/s/4NLAPpg17z96SXiI1XYEWg',\n" +
'    [Symbol(kCapture)]: false\n' +
'  },\n' +
'  cause: Error: read ECONNRESET\n' +
'      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {\n' +
'    errno: -54,\n' +
"    code: 'ECONNRESET',\n" +
"    syscall: 'read'\n" +
'  }\n' +
'}')
at new NodeError (node:internal/errors:372:5)
at Worker.emit (node:events:516:17)
at [kOnErrorMessage] (node:internal/worker:290:10)
at [kOnMessage] (node:internal/worker:301:37)
at MessagePort.<anonymous> (node:internal/worker:202:57)
at [nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
at exports.emitMessage (node:internal/per_context/messageport:23:28)

**Comment by xiaoguyu** [comment]
很抱歉，我没有mac环境，所以无法确认您的问题。如果您已经修复了问题，欢迎提PR
