### ISSUE TITLE
批量下载：提示下载超时，未监测到公众号文章

### ISSUE THREAD

**Issue by doitzhangwangcheng** [xiaoguyu/wechatDownload#11]
windows 微信版本 3.9.7.29  wechatDownload 版本 v.1.4.4

使用批量下载功能，证书也安装了，下载配置中只修改了下载范围，时间选择7日内，其他无任何改动，按照README提示，无法正常工作

提示：
下载来源为网络

代理开启成功，准备批量下载...

请在微信打开任意一篇需要批量下载的公号的文章

别偷懒，已经打开的不算...

批量下载超时，未监测到公号文章！

我想问下：是否和微信版本有关？如果是，你的README中的微信版本是多少，

**Comment by xiaoguyu** [comment]
与微信版本无关，可以试试监控下载功能，如果也不行，那就是证书没有正确安装

**Comment by dan-hsc** [comment]
是不是win11的不行，win11的反复弄了几次证书都没成功，win10上一次就好了。

**Comment by doubletree6** [comment]
我也是win11，打开公众号文章以后点刷新，会出现一个不信任网页，点高级-前往，wechatdownload就识别了

**Comment by xiaoguyu** [comment]
![ca](https://github.com/xiaoguyu/wechatDownload/assets/22335025/dfef3122-9d70-498c-8649-301ce839cf9c)

**Comment by xiaoguyu** [comment]
我今天用win 11（21H2 专业版）测试了下，是可以正常使用的，请确保证书安装时选的存储位置是选受信任的根证书颁发机构

**Comment by doitzhangwangcheng** [comment]
感谢，按照你说的安装根证书，解决了

**Comment by dan-hsc** [comment]
win11没问题，是我自己电脑的问题，现在已经没问题了。

**Comment by chilam85** [comment]
不行的，关注一下自己是不是开了其它代理，走的是不是微信下载这个代理
