### ISSUE TITLE
批量下载失败，错误信息：unknown error

### ISSUE THREAD

**Issue by adm1n007** [xiaoguyu/wechatDownload#12]
下载来源为网络

代理开启成功，准备批量下载...

请在微信打开任意一篇需要批量下载的公号的文章

别偷懒，已经打开的不算...

已监测到文章，请确认是否批量下载该文章所属公号

获取文章列表失败，错误信息：unknown error

批量下载完成，共0篇文章，耗时0.23秒

log：

[2023-10-10 23:06:41.477] [error] [
  '获取文章列表失败',
  'https://mp.weixin.qq.com/mp/profile_ext?action=getmsg&f=json&count=10&is_ok=1&__biz=MzU2NzEwMDc1MA==&key=b8982b21b1d079659f80a14401c1b32b429cf05b13e72337bac3433c27616930ae5e3392a663bb64d47b651c07f7c037e0c5979884e982f77a79c29b249fb2e67062712ccad41d630f372fd166b8a8936fa96b18a9225e7fef6675b473c74ae292c937a5e11a51b58edf28037d4236803b38b75edc0ab0c7dde703d3b63dda0b&uin=MTU3MzY3MjU1&pass_ticket=8sZkL3P6GeLFMmugNRCJkZoEyi9wot%2BZeWxcGeozHWO7uSg%2BIupMFEGr4hwF2Roy&offset=0',
  { ret: -6, errmsg: 'unknown error', home_page_list: [] }
]
[2023-10-10 23:06:41.479] [info]  [ 'resp', 2, '获取文章列表失败，错误信息：unknown error', null ]
[2023-10-10 23:06:41.480] [info]  [ 'resp', 4, '批量下载完成，共0篇文章，耗时0.23秒', null ]
[2023-10-10 23:06:41.480] [info]  [ 'resp', 5, '', null ]

**Comment by xiaoguyu** [comment]
参考这个 #7
