### ISSUE TITLE
微信号被封

### ISSUE THREAD

**Issue by ywzhaiqi** [xiaoguyu/wechatDownload#16]
大概是使用了批量下载或评论下载，微信突然提示被封，使用了 第三方工具...  万幸，勾选几个规则后，微信可正常登陆。不敢用工具了。
特此说明 可能存在的风险。

**Comment by xiaoguyu** [comment]
其他同学如果出现微信异常，也在此贴反馈一下吧

**Comment by ywzhaiqi** [comment]
今天又被封了一次，但这段时间没用这个工具，应该不是这工具问题。
可能是用了前段时间 微信小程序 调出开发工具 导致的。
