### ISSUE TITLE
无法监听到文章

### ISSUE THREAD

**Issue by Fortune857** [xiaoguyu/wechatDownload#17]
![image](https://github.com/xiaoguyu/wechatDownload/assets/101683922/b8f671a7-c3ec-4e9f-b0a8-9e1a8e399105)
按照说明操作,但是还是不能监测到文章,不能批量下载

**Comment by xiaoguyu** [comment]
去翻翻其他issues，这个问题已经不少人问过了

**Comment by JohnGuoy** [comment]
同样不能批量下载，也不能监控下载

我的系统是win10，微信PC版版本是3.9.7.25

**Comment by xiaoguyu** [comment]
> 同样不能批量下载，也不能监控下载，证书已经正确安装到“受信任的根证书颁发机构”下
> 
> 我的系统是win10，微信PC版版本是3.9.7.25
> 
> 是否应该更新一下内部爬虫代码？

我也是win10，软件版本v1.4.51，微信版本3.9.7.29，是可以正常使用的

**Comment by benpaoniu** [comment]
经我个人测试，可能跟选择的网络有关系，监听不到的朋友，可以选择其他网络其他wifi试一下。
