### ISSUE TITLE
批量下载+下载来源的问题或者不解

### ISSUE THREAD

**Issue by it985** [xiaoguyu/wechatDownload#18]
描述：
下载来源数据库+监控下载，正常下载，正常入库
![image](https://github.com/xiaoguyu/wechatDownload/assets/62421120/da3f44b8-b1e6-494e-85d5-5c5e9ef84629)

当设置：下载来源数据库+批量下载时，自动下载数据库中的数据；并没有像批量下载+下载来源网络，那样下载

**Comment by xiaoguyu** [comment]
没搞懂你的意思
下载来为源数据库用于将数据中心的数据转换成文档（一般你们也用不到这功能）
下载来为网络就是正常的下载
监控下载不受下载来源影响，效果和下载来为网络一样

**Comment by it985** [comment]
> 没搞懂你的意思 下载来为源数据库用于将数据中心的数据转换成文档（一般你们也用不到这功能） 下载来为网络就是正常的下载 监控下载不受下载来源影响，效果和下载来为网络一样

就是使用批量+数据库的时候，下载是数据库中的来源是监控的
并不能使用批量入库

**Comment by it985** [comment]
![](https://article.biliimg.com/bfs/article/192b142d6a5123903bdcee086a4272ac300767383.gif@1e_1c.webp)
![](https://article.biliimg.com/bfs/article/d02f75445cb48ced53a05c2fe105384a300767383.gif@1e_1c.webp)
![](https://article.biliimg.com/bfs/article/52ed3d93b34f0cea4749cc7a7156f06c300767383.gif@1e_1c.webp)

**Comment by xiaoguyu** [comment]
按照你的需求，请使用 下载来源（网络） + 勾选保存至Mysql + 批量下载

**Comment by it985** [comment]
问题已解决，是我理解不当
