### ISSUE TITLE
勾选了下载评论选项，下载后的文档里没有评论

### ISSUE THREAD

**Issue by dulcan1988** [xiaoguyu/wechatDownload#23]
勾选了下载评论选项，下载后的文档里没有评论

**Comment by xiaoguyu** [comment]
批量下载和监控下载才支持评论

**Comment by dulcan1988** [comment]
是用的批量下载功能

**Comment by xiaoguyu** [comment]
哪个文章没有评论的，链接发一下

**Comment by dulcan1988** [comment]
https://mp.weixin.qq.com/s/q3ciAfejk6QaftaXr8GKqA

**Comment by dulcan1988** [comment]
电脑版微信上看的是有评论，复制链接出来就没评论了，奇怪
![QQ截图20231109101256](https://github.com/xiaoguyu/wechatDownload/assets/17426274/77e46d5d-56a8-4c98-8e56-fc3e6731cd34)

**Comment by xiaoguyu** [comment]
下载评论和下载评论回复都要勾选上，然后使用批量下载或者监控下载

**Comment by dulcan1988** [comment]
是都勾上了，也用的批量下载。你试了可以下载评论吗？你关注下“唐书房”公众号试试

**Comment by xiaoguyu** [comment]
可以下载，你用最新版的软件试试吧。

**Comment by dulcan1988** [comment]
过了一段时间再试可以了，更做任何修改。哈哈，玄学
