### ISSUE TITLE
下载某公众号文章，终是下载一二十篇就停了

### ISSUE THREAD

**Issue by longfei796** [xiaoguyu/wechatDownload#27]
蛋挞怪怪屋的公众号
希望增加检测公众号发布文章数量的功能

**Comment by longfei796** [comment]
![mmexport1701766946914](https://github.com/xiaoguyu/wechatDownload/assets/117554192/87b18212-7926-4c7d-8876-8e9eb28243f8)
![mmexport1701766944046](https://github.com/xiaoguyu/wechatDownload/assets/117554192/31e27f88-4e14-4c56-9749-bdda7d55feb3)
[2023-12-5.log](https://github.com/xiaoguyu/wechatDownload/files/13557593/2023-12-5.log)

**Comment by xiaoguyu** [comment]
你说的点击没反应，应该是触发了公众号的反爬机制了，然后需要等待60秒
![Snipaste_2023-12-06_13-48-44](https://github.com/xiaoguyu/wechatDownload/assets/22335025/14d5acf6-e901-4038-87e3-1dcc5e1ab259)
