### ISSUE TITLE
建议不用一篇文章一个文件夹

### ISSUE THREAD

**Issue by appsdog** [xiaoguyu/wechatDownload#28]
**建议 不用一篇文章一个文件夹，** 批量下载情况下，以公众号名字为文件夹，导出的HTML或PDF 一目了然，方便操作。
因为如果批量下载多个公众号，导出HTML或PDF全设置在一个文件夹，不好区分和归类。
公众号有更新，需要重新下载一遍了吧？

**Comment by xiaoguyu** [comment]
一篇文章一个文件夹是因为下载的图片和音频也放在同一个文件夹，所以这个功能暂时不会上

**Comment by benpaoniu** [comment]
软件非常棒！感谢开发者！如果不考虑调整，又能考虑大家的需求，可以有第三选项哦，即按公众号来命名大的文件夹，各篇文章按开发者的逻辑一样还是一篇文章一个文件夹。只不过变成了子文件夹。

**Comment by xiaoguyu** [comment]
> 软件非常棒！感谢开发者！如果不考虑调整，又能考虑大家的需求，可以有第三选项哦，即按公众号来命名大的文件夹，各篇文章按开发者的逻辑一样还是一篇文章一个文件夹。只不过变成了子文件夹。

好提议，我找时间改一下

**Comment by xiaoguyu** [comment]
已添加分类功能，可在设置中勾选

**Comment by nop4LOL** [comment]
> 已添加分类功能，可在设置中勾选

没有啊，设置中没有这个选项
