### ISSUE TITLE
可以下载单篇文章，但批量下载提示“获取文章列表失败，错误信息：no session”

### ISSUE THREAD

**Issue by GoTop** [xiaoguyu/wechatDownload#32]
wechatDownload版本1.4.8
电脑系统 win11 64bit
微信版本 3.9.8.25（目前最新版）

软件界面上提示的信息为：
> 下载来源为网络
代理开启成功，准备批量下载...
请在微信打开任意一篇需要批量下载的公号的文章
别偷懒，已经打开的不算...
批量下载超时，未监测到公号文章！
已监测到文章，请确认是否批量下载该文章所属公号
获取文章列表失败，错误信息：no session
批量下载完成，共0篇文章，耗时0.24秒

log文件：
[2024-1-16.log](https://github.com/xiaoguyu/wechatDownload/files/13944155/2024-1-16.log)

**Comment by xiaoguyu** [comment]
两种情况：
1. 之前批量下过不少文章，接口被封了（这种缓几天就恢复了）
2. 账号不行（这个我没遇到，不清楚）
可以参考 #21

**Comment by GoTop** [comment]
> 两种情况：
> 
> 1. 之前批量下过不少文章，接口被封了（这种缓几天就恢复了）
> 2. 账号不行（这个我没遇到，不清楚）
>    可以参考 [获取文章列表失败，错误信息：no session #21](https://github.com/xiaoguyu/wechatDownload/issues/21)

我之前没有批量下载成功过，估计不是第一个问题
我的微信账号也就自己日常个人使用，应该挺正常的啊

**Comment by GoTop** [comment]
今天看到另一个issue里有为兄弟说再次尝试，可以下载成功。我也试了一下，确实可以了。

看来可能是微信对账号的限制问题
