### ISSUE TITLE
请问以前询问触发反扒机制的时候说分段下载，请问间隔多少合适？

### ISSUE THREAD

**Issue by longfei796** [xiaoguyu/wechatDownload#35]
线程配置多少合适
微信文章是从新到旧还是从旧到新，从旧到新的话，最旧的文章该如何得知，我用的老版微信没有更新，是更新后微信就有功能了吗

**Comment by xiaoguyu** [comment]
1、线程多少随你，因为我也不知道多少合适
2、是从新到旧获取的，爬虫返回的数据中有一个字段标识能否继续翻页，与微信版本无关
