### ISSUE TITLE
获取数量不对，少了哦，才11篇，其实有100多篇哦

### ISSUE THREAD

**Issue by benwu007** [xiaoguyu/wechatDownload#36]
获取数量不对，少了哦，才11篇，其实有100多篇哦

**Comment by xiaoguyu** [comment]
请描述清楚你的问题，设置中心是怎么配置的，获取哪个公号的文章
如果嫌麻烦就直接上传日志文件

**Comment by benwu007** [comment]
本人已经收到您的来信，会认真阅读，谢谢你的来信！(⊙o⊙)…
