### ISSUE TITLE
《海报格式页面》下载错误

### ISSUE THREAD

**Issue by rrjz** [xiaoguyu/wechatDownload#37]
wechatDownload版本1.4.8
电脑系统 win10 64bit
微信版本 3.9.9.35

海报格式页面的微信文章，最近下载已经不行。

**具体问题：**
文章有图片软件获取为0/文字也不会获取，导出后的HTML文字/图片为空白。

**示范文章链接：** https://mp.weixin.qq.com/s/FKkNEbhu35ojI7pn97SYzw

下载后的HTML如下图：
----
![微信截图_20240204110802](https://github.com/xiaoguyu/wechatDownload/assets/11684731/3709fb3c-cf56-4af2-9674-fee2ba2f37f5)
----

**Comment by xiaoguyu** [comment]
v1.4.9版本已经修复
