### ISSUE TITLE
【建议】批量下载添加屏蔽/指定作者功能

### ISSUE THREAD

**Issue by ZhFuwe-Github** [xiaoguyu/wechatDownload#38]
感谢您的开发！

**Comment by xiaoguyu** [comment]
是想要过滤掉广告吧，我年后找时间改下

**Comment by snomgq** [comment]
有的下载的html文件段落不分开，合成一整段了

**Comment by xiaoguyu** [comment]
> 有的下载的html文件段落不分开，合成一整段了

麻烦提供下段落不分开的网页的链接

**Comment by snomgq** [comment]
> > 有的下载的html文件段落不分开，合成一整段了
> 
> 麻烦提供下段落不分开的网页的链接

https://mp.weixin.qq.com/s/QGuyIhejh6oqomxRz0VpWg

像这种的，就算右键复制，然后在word里原格式粘贴，也是不分段

**Comment by xiaoguyu** [comment]
v1.5.1版本新增了过滤规则，你可以用以下规则来过滤作者。详情请看readme

```json
{
    "auth": {
        "exclude": ["张三", "李四"]
    }
}
```
