### ISSUE TITLE
希望增加另存为word功能和内嵌图片到HTML功能。

### ISSUE THREAD

**Issue by bayosolin** [xiaoguyu/wechatDownload#39]
希望增加另存为word功能和内嵌图片到HTML功能。准备下载一些硬货公众号文章，编成电子书，pdf格式，合并后放到手机里，阅读不方便，想用word格式，转成epub，或者HTML直接转成epub。谢谢。

**Comment by xiaoguyu** [comment]
你可以考虑下pdf转epub

**Comment by bayosolin** [comment]
> 你可以考虑下pdf转epub

试过了，pdf排版变了很多，转换过来也是不太友好。

**Comment by xiaoguyu** [comment]
1. 暂不考虑html内嵌图片
2. 后续可能会保存成word格式
3. 后续可能会支持将整个文件夹的html转成epub

**Comment by bayosolin** [comment]
这个功能好，直接转成epub。辛苦了

**Comment by xiaoguyu** [comment]
v1.7.0版本已支持通过 html 生成 epub
