### ISSUE TITLE
《反馈》有一种文章保存乱码

### ISSUE THREAD

**Issue by rrjz** [xiaoguyu/wechatDownload#41]
文章地址：https://mp.weixin.qq.com/s/vLuVL5owS5VdTDmMRzu3vQ

这种文章为公众号博主发的纯文字信息。

最后的软件的保存情况如下图：
![image](https://github.com/xiaoguyu/wechatDownload/assets/11684731/c41bf1f3-2b11-41c3-a0f0-28039a8ab988)
----
文件夹情况如下：文件名也是乱码，没有时间开头的文件名
![image](https://github.com/xiaoguyu/wechatDownload/assets/11684731/e09deabb-9d12-41e4-9fa6-e4825346f1cc)

**Comment by xiaoguyu** [comment]
收到，下版本修复

**Comment by xiaoguyu** [comment]
v1.4.10版本已修复此问题
