### ISSUE TITLE
《反馈》部分年份的海报格式文章提取正文失败

### ISSUE THREAD

**Issue by rrjz** [xiaoguyu/wechatDownload#42]
**文章地址：** https://mp.weixin.qq.com/s/fzPkvEyECe-MYE_OTHLS-w
（该文章写于：2021-06-13）

**反馈：**
2024年的最新的海报格式文章下载没有问题，
但是今天想下载再早年份一点的海报格式文章，发现软件提示**提取正文失败**

----

![image](https://github.com/xiaoguyu/wechatDownload/assets/11684731/93806c5a-b0cf-4668-83b1-912151d51787)

----
软件版本：1.4.10
系统：win10

**Comment by xiaoguyu** [comment]
v1.4.11 版本已修复
