### ISSUE TITLE
批量下载超时，未监测到公号文章！已经安装好证书，可以单篇下载

### ISSUE THREAD

**Issue by JunyanNiu** [xiaoguyu/wechatDownload#46]
Win10 64
VX：3.9.9.43
版本：1.4.12
[2024-3-15.log](https://github.com/xiaoguyu/wechatDownload/files/14621433/2024-3-15.log)

**Comment by xiaoguyu** [comment]
安装证书需要管理员权限来启动软件。
如果已经安装好证书，批量下载超时，那用监控下载试试，如果都不行，那就是证书的问题

**Comment by Acklee** [comment]
是不是需要先点监控下载，再点批量下载呀？我直接点批量下载，也是无法监测到。先监控下载，再批量下载就可以了。

**Comment by xiaoguyu** [comment]
> 是不是需要先点监控下载，再点批量下载呀？我直接点批量下载，也是无法监测到。先监控下载，再批量下载就可以了。

不需要，你这种直接批量下载就行。有超时处理，15秒内检测不到微信文章就会关闭

**Comment by xiaoguyu** [comment]
没后续，关闭issue
