### ISSUE TITLE
获取文章数目错误

### ISSUE THREAD

**Issue by Acklee** [xiaoguyu/wechatDownload#47]
![image](https://github.com/xiaoguyu/wechatDownload/assets/6162014/a11a79d9-a7d0-4e7d-87d2-cc280d7fa942)
只获取到了6篇文章

**Comment by xiaoguyu** [comment]
请去`设置中心`确认`下载范围`是不是选的全部

**Comment by Acklee** [comment]
修改范围可以了，感谢！
