### ISSUE TITLE
批量下载的时候.微信公众号目录分类后,只会下载默认目录的,其他目录的文章下载不到.希望能把其他目录的也能下载

### ISSUE THREAD

**Issue by babywen** [xiaoguyu/wechatDownload#48]

**Comment by xiaoguyu** [comment]
没看懂你的意思。我的逻辑是能提取到公众号名字就按公众号名字分类，提取不到的都放在**保存路径**

**Comment by babywen** [comment]
如公众号:lv51933
使用批量下载的时候只能下载3篇文章.
我怀疑是博主进行了文章目录分类,或者其他设置导致了不能下载全部文章
![文章目录分类](https://github.com/xiaoguyu/wechatDownload/assets/14839032/f5526282-5379-4769-8b54-807dfa7ba1b7)
![批量下载图](https://github.com/xiaoguyu/wechatDownload/assets/14839032/b4838fb0-7324-41d7-8368-96e1dbec9a3b)
![下载范围设置](https://github.com/xiaoguyu/wechatDownload/assets/14839032/4b146550-1406-4071-8928-ce5d1fd26b50)

**Comment by xiaoguyu** [comment]
这个公众号有点特殊，我也没法处理，你只能用监控下载一篇一篇下载了。因为他是历史文章页面长这样
![Snipaste_2024-03-28_10-44-12](https://github.com/xiaoguyu/wechatDownload/assets/22335025/f7313448-25b8-48c5-8d6b-c4692a7ecbc0)

**Comment by babywen** [comment]
好的,明白.感谢你的排查解疑.谢谢
