### ISSUE TITLE
批量下载选择有评论和回复但经常采集不到评论，单次只下载两到三篇也不行，换了几个微信号也不行

### ISSUE THREAD

**Issue by Git-James23** [xiaoguyu/wechatDownload#49]
由于有些公众号文章的评论区有很多比正文还有价值的内容，所以会选择勾选“有评论和回复”，上个月批量下载一两百篇都能正常采集到所有评论，但现在更新到1.5.1版勾选了评论也经常采集不到，一开始以为是限制爬虫所以只几篇几篇的下也不行，然后换了网络环境也不行，以为是微信号被限制了于是换了其他微信号登录微信尝试也无效（还新注册了一个全新的微信，结果新微信号采集时直接显示“获取文章列表失败，错误信息：unknown error”不知道为什么）。

希望大佬可以解决或者解答这个问题，感谢！！

**Comment by xiaoguyu** [comment]
评论采集不到可以的可以发一下文章链接，我测试下。
至于unknown error的，可以看下 #21

**Comment by Git-James23** [comment]
> 评论采集不到可以的可以发一下文章链接，我测试下。 至于unknown error的，可以看下 #21

试试这篇以及这个作者的其他文章
https://mp.weixin.qq.com/s/U-gEgMsvB8OlrfRwfr9Rww

**Comment by xiaoguyu** [comment]
我测试下在7天没的文章，都是没问题的。
如果文章内容正常，只是没评论，那我再看看。
如果是文章都获取不到，那就是你微信历史文章的接口被封了，需要等一两周才能解。
这期间请用监控下载一篇一篇来下载。

**Comment by xiaoguyu** [comment]
没救，将就用吧，我下个版本加上下载评论的调试日志，到时候再看看。

**Comment by Git-James23** [comment]
> 没救，将就用吧，我下个版本加上下载评论的调试日志，到时候再看看。

好吧......坐等大哥更新

**Comment by xiaoguyu** [comment]
你好，你发一下日志给我看看。哪天下载评论出问题，就发哪天的日志就行。在设置中心有打开日志文件夹的按钮。

**Comment by Git-James23** [comment]
> 你好，你发一下日志给我看看。哪天下载评论出问题，就发哪天的日志就行。在设置中心有打开日志文件夹的按钮。

好的
[2024-3-25.log](https://github.com/xiaoguyu/wechatDownload/files/14942550/2024-3-25.log)
