### ISSUE TITLE
无法抓取历史文章

### ISSUE THREAD

**Issue by Unword** [xiaoguyu/wechatDownload#5]
从1.4开始，那个版本就无法抓全部文件，单线程或者多线程，按日期或者全部都一样，只有20个文章被下载

**Comment by xiaoguyu** [comment]
请提供下你的设置中心的截图，最好能提供日志文件，路径是C:\Users\xxx\AppData\Roaming\wechatDownload\logs

**Comment by Unword** [comment]
大概懂了，明天上传有问题的机子截图。
家里的机子没问题。
但是公司的昨天装了一个最新的nodejs，而且还是20.5.1，而且还选择了安装必备的插件

**Comment by xiaoguyu** [comment]
> [2023-8-23.log](https://github.com/xiaoguyu/wechatDownload/files/12420883/2023-8-23.log) ![图片](https://user-images.githubusercontent.com/48384420/262720898-ed00ac2c-db5d-4dc0-b8d5-f8427ccaec3d.png) 好吧，家里的下了30篇停止了。

批量下载需要获取微信的key，key的有效期在半小时以内（我预估，实际没具体测试过）。你设置了单线程、下载间隔30秒，下载了30篇就15分钟了（key失效了），如果你怕下载太快，建议下载间隔填1000（也就是1秒）

**Comment by Unword** [comment]
我记得已经增加过自动获取key的功能吧，还是我搞错了。
没办法自动获取的吗？

**Comment by xiaoguyu** [comment]
> 我记得已经增加过自动获取key的功能吧，还是我搞错了。 没办法自动获取的吗？

点击批量下载按钮就是为了通过代理获取key，每次批量下载也只会获取一次key。目前还没有好的方式对key续期或者重新获取key，我建议你自定义下载范围，分批下载。如果没有其他问题，那我就关闭此issue了

**Comment by Unword** [comment]
再新增一个问题。
就是将间隔调小后，比如1分钟一次，半小时共30次。
每次抓取10个文章，下载后，下次继续抓取的是20个，其中前10个就是前面下载过的，会显示已存在，跳过。
希望每次按半小时除以间隔一次性获取要下载的列表。
