### ISSUE TITLE
反爬机制记录

### ISSUE THREAD

**Issue by Lengso** [xiaoguyu/wechatDownload#50]
触发公众号的反爬机制，停止采集!

建议设置合理的下载间隔

建议选择合适的下载范围，按区间分批下载

---------------------------------------------------
单公众号批量下载出现提示就停止了，如何能根据上一次下载的位置继续下载。

**Comment by xiaoguyu** [comment]
去设置中心
1. 勾选跳过现有文章
2. 下载范围选自定义，改一下结束时间

**Comment by Lengso** [comment]
收到，分批次建议数值多少合适？

**Comment by xiaoguyu** [comment]
我也不知道，没测试过。我用默认的
