### ISSUE TITLE
批量下载超时，未监测到公号文章！

### ISSUE THREAD

**Issue by venyao** [xiaoguyu/wechatDownload#6]
我在使用批量下载功能的时候遇到问题。明明已经打开公众号文章了（是在微信中打开的，不是在浏览器中打开的），而且是在点击“批量下载”按钮之后，我才点击打开公众号文章的。
后来发现：
当打开文章是微信浏览器提示页面不安全，然后要点击继续前往，这样的情况下，wechatDownload就能检测到公众号文章了。
但是，这样的情况很少发生，就导致检测不到。怎么办呢？

**Comment by xiaoguyu** [comment]
确认下安装证书的时候有没有把证书存储在**受信任的根证书颁发机构**中，项目介绍中有安装证书的步骤

**Comment by it985** [comment]
os:win11
wx:3.9.6.33
![未下载 00_00_00-00_00_30](https://github.com/xiaoguyu/wechatDownload/assets/62421120/a23a0638-490f-41c2-841c-1ee9f9a4462a)

**Comment by xiaoguyu** [comment]
![Snipaste_2023-09-01_18-00-34](https://github.com/xiaoguyu/wechatDownload/assets/22335025/85a80547-9244-47b1-8845-ba464fdaee8c)

**Comment by it985** [comment]
谢谢了！这个问题解决了。

**Comment by tianyuchou** [comment]
> 谢谢了！这个问题解决了。

怎么解决的，我和你视频出现的问题一样

**Comment by it985** [comment]
> ![Snipaste_2023-09-01_18-00-34](https://user-images.githubusercontent.com/22335025/264990575-85a80547-9244-47b1-8845-ba464fdaee8c.jpg)



> > 谢谢了！这个问题解决了。
> 
> 怎么解决的，我和你视频出现的问题一样

证书安装错误，安装这个方式安装即可
