### ISSUE TITLE
获取文章列表失败，错误信息：unknown error

### ISSUE THREAD

**Issue by venyao** [xiaoguyu/wechatDownload#7]
这个是不是被微信的”反爬机制“封了？
昨天还能正常用，今天就不行了。
有解决办法吗？

**Comment by perphia** [comment]
下午测试监听、批量下载都失效了

**Comment by xiaoguyu** [comment]
> 这个是不是被微信的”反爬机制“封了？ 昨天还能正常用，今天就不行了。 有解决办法吗？

出现unknown error都是微信接口被封了，等几天再用吧

**Comment by xiaoguyu** [comment]
> 下午测试监听、批量下载都失效了

请确保你按项目描述正确安装了证书，如果还不行，请详细描述你的环境和提供日志

**Comment by venyao** [comment]
谢谢~
