### ISSUE TITLE
mysql链接问题

### ISSUE THREAD

**Issue by it985** [xiaoguyu/wechatDownload#8]
![2 00_00_00-00_00_30](https://github.com/xiaoguyu/wechatDownload/assets/62421120/a859f81b-3e4c-4e4e-bbc0-8467d0629bfb)
![23](https://github.com/xiaoguyu/wechatDownload/assets/62421120/f52b4fd5-f87e-40a9-805d-488c8a246d5e)
os：win11 
软件版本：142
mysql：8.0.28

**Comment by xiaoguyu** [comment]
下个版本支持mysql8

**Comment by it985** [comment]
谢谢回复

**Comment by xiaoguyu** [comment]
1.4.3版本已添加对mysql8的支持
